"""Benchmark runner CLI — context sweep, warmup, repeats, percentiles.

Implements the measurement protocol from ``docs/METRICS.md`` and emits
schema-conformant CSV via ``bench/schema.py`` (bead ``ob-ljh``).

**Design: pluggable backend.** The harness defines *how* to measure
(warmup → timed repeats → per-repeat rows), not *what* to run.  An
``InferenceBackend`` protocol is injected so the same harness works on
NPU, GPU, CPU, llama.cpp, or transformers — each device plugs in its own
backend.  The harness's job is the measurement contract; the backend's
job is the actual inference.

Usage::

    # full sweep with a real backend
    python -m bench.harness \\
        --backend my_backend \\
        --model-checkpoint Qwen/Qwen3.5-4B \\
        --context-lengths 4096,32768,131072,262144 \\
        --warmups 3 --repeats 5 \\
        --device generic_aarch64 \\
        --engine-gdn cpu --engine-full-attention cpu \\
        --quantization fp16 \\
        --output results/raw/my_run.csv

    # smoke test with a synthetic backend (no model needed)
    python -m bench.harness --backend synthetic --repeats 3 --context-lengths 4096 \\
        --model-checkpoint test --device x86_reference \\
        --engine-gdn cpu --engine-full-attention cpu \\
        --quantization fp16 --output /tmp/smoke.csv
"""

from __future__ import annotations

import argparse
import math
import os
import subprocess
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Protocol

# Make schema importable when run as a script from the repo root.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from schema import (  # noqa: E402
    CANONICAL_CONTEXT_LENGTHS,
    ResultRow,
    SchemaValidationError,
    validate_row,
    write_csv,
)

# ---------------------------------------------------------------------------
# Metric definitions (docs/METRICS.md sections 3–4)
# ---------------------------------------------------------------------------


@dataclass
class TimingResult:
    """Raw timing from one inference run.

    All times are wall-clock seconds measured by the harness (not the backend).
    The backend reports *when* key events happened; the harness records them.

    - ``t_submit``   : request submitted to backend
    - ``t_first_token`` : first generated token produced (= end of prefill)
    - ``t_last_token``  : last requested token produced (= end of decode)
    - ``prompt_tokens`` : number of tokens in the prompt (prefill input)
    - ``decode_tokens`` : number of tokens generated by decode (excludes
      the first prefill-produced token, per METRICS.md §4)
    """

    t_submit: float
    t_first_token: float
    t_last_token: float
    prompt_tokens: int
    decode_tokens: int


@dataclass
class MemorySnapshot:
    """Peak memory for one component during one phase (bytes)."""

    component: str  # "weights", "kv_cache", "recurrent_state"
    phase: str  # "prefill" or "decode"
    peak_bytes: int


@dataclass
class RunResult:
    """Everything the harness needs from one repeat of one context length."""

    timing: TimingResult
    memory: list[MemorySnapshot] = field(default_factory=list)
    energy_prefill_joules: float | None = None
    energy_decode_joules: float | None = None
    notes: str = ""


# ---------------------------------------------------------------------------
# Backend protocol
# ---------------------------------------------------------------------------


class InferenceBackend(Protocol):
    """What a backend must provide for the harness to measure it.

    The harness calls these methods in this order for each (context_length,
    repeat) pair:

    1. ``load(model_checkpoint, quantization, context_length)``
    2. ``prefill(prompt_tokens)`` → first token produced (timing recorded)
    3. ``decode(n_decode_tokens)`` → remaining tokens (timing recorded)
    4. ``get_memory(phase)`` → optional memory snapshots
    5. ``get_energy(phase)`` → optional energy readings
    """

    def load(
        self,
        model_checkpoint: str,
        quantization: str,
        context_length: int,
    ) -> None: ...

    def prefill(self, prompt_tokens: int) -> float:
        """Process the prompt and return wall-clock time of first token.

        The harness records ``t_submit`` before calling this and
        ``t_first_token`` after it returns.
        """
        ...

    def decode(self, n_tokens: int) -> float:
        """Generate ``n_tokens`` decode tokens, return wall-clock time.

        The harness records ``t_last_token`` after this returns.
        """
        ...

    def get_memory(self, phase: str) -> list[MemorySnapshot]: ...

    def get_energy(self, phase: str) -> float | None: ...


# ---------------------------------------------------------------------------
# Synthetic backend (for testing / CI smoke runs — no model required)
# ---------------------------------------------------------------------------


class SyntheticBackend:
    """Fake backend that sleeps proportionally — for CI and local testing.

    Produces deterministic, realistic-looking timings so the CSV pipeline
    can be tested without torch or model weights.  Prefill is modelled as
    O(prompt_tokens) at ~500 tok/s; decode as O(n_tokens) at ~20 tok/s.
    """

    PREFILL_RATE = 500.0  # tokens/sec (synthetic)
    DECODE_RATE = 20.0  # tokens/sec (synthetic)

    def load(self, model_checkpoint: str, quantization: str, context_length: int) -> None:
        pass  # nothing to load

    def prefill(self, prompt_tokens: int) -> float:
        return prompt_tokens / self.PREFILL_RATE

    def decode(self, n_tokens: int) -> float:
        return n_tokens / self.DECODE_RATE

    def get_memory(self, phase: str) -> list[MemorySnapshot]:
        return []

    def get_energy(self, phase: str) -> float | None:
        return None


# ---------------------------------------------------------------------------
# Harness core
# ---------------------------------------------------------------------------


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _git_sha() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short=7", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
            check=True,
        )
        return result.stdout.strip()
    except Exception:
        return "unknown"


def _percentile(values: list[float], pct: float) -> float:
    """Compute the pct-th percentile (0–100) of a list, nearest-rank method."""
    if not values:
        return float("nan")
    sorted_vals = sorted(values)
    n = len(sorted_vals)
    if n == 1:
        return sorted_vals[0]
    # Nearest-rank: ceil(pct/100 * n) - 1, clamped to [0, n-1]
    rank = max(1, math.ceil(pct / 100.0 * n))
    return sorted_vals[min(rank, n) - 1]


@dataclass
class HarnessConfig:
    """All parameters that define one benchmark run."""

    model_checkpoint: str
    device: str
    engine_gdn: str
    engine_full_attention: str
    quantization: str
    context_lengths: list[int]
    warmups: int = 3
    repeats: int = 5
    decode_tokens: int = 256  # N-1 decode tokens (METRICS.md §4: N=257, so 256 decode)
    run_id: str = ""
    output: str = ""
    manifest_ref: str = ""

    def __post_init__(self) -> None:
        if self.warmups < 0:
            raise ValueError(f"warmups must be >= 0, got {self.warmups}")
        if self.repeats < 5:
            raise ValueError(
                f"repeats must be >= 5 for percentile reporting "
                f"(METRICS.md §9: 'report percentiles and repeat counts, "
                f"never a single best run'), got {self.repeats}"
            )
        if not self.run_id:
            stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
            self.run_id = f"{self.device}_{stamp}_{_git_sha()}"
        if not self.manifest_ref:
            self.manifest_ref = f"results/manifests/{self.run_id}.json"


def run_single(
    backend: InferenceBackend,
    config: HarnessConfig,
    context_length: int,
    repeat_index: int,
) -> RunResult:
    """Execute one repeat at one context length and return raw timings."""
    # Load the model (warmup loads too; we discard those results)
    backend.load(config.model_checkpoint, config.quantization, context_length)

    # Prefill: measure time to first token
    t_submit = time.perf_counter()
    backend.prefill(context_length)
    t_first_token = time.perf_counter()

    # Decode: generate decode_tokens tokens (N-1 from METRICS.md)
    backend.decode(config.decode_tokens)
    t_last_token = time.perf_counter()

    timing = TimingResult(
        t_submit=t_submit,
        t_first_token=t_first_token,
        t_last_token=t_last_token,
        prompt_tokens=context_length,
        decode_tokens=config.decode_tokens,
    )

    # Optional measurements
    prefill_mem = backend.get_memory("prefill")
    decode_mem = backend.get_memory("decode")
    energy_prefill = backend.get_energy("prefill")
    energy_decode = backend.get_energy("decode")

    return RunResult(
        timing=timing,
        memory=prefill_mem + decode_mem,
        energy_prefill_joules=energy_prefill,
        energy_decode_joules=energy_decode,
    )


def result_to_rows(
    result: RunResult,
    config: HarnessConfig,
    context_length: int,
    repeat_index: int,
    repeat_count: int,
) -> list[ResultRow]:
    """Convert one RunResult into schema-conformant ResultRow(s)."""

    ts = _utc_now()
    sha = _git_sha()
    common = dict(
        run_id=config.run_id,
        timestamp=ts,
        git_sha=sha,
        manifest_ref=config.manifest_ref,
        device=config.device,
        engine_gdn=config.engine_gdn,
        engine_full_attention=config.engine_full_attention,
        model_checkpoint=config.model_checkpoint,
        quantization=config.quantization,
        context_length=context_length,
        repeat_index=repeat_index,
        repeat_count=repeat_count,
    )

    rows: list[ResultRow] = []

    # --- prefill_tokens_per_sec ---
    prefill_dur = result.timing.t_first_token - result.timing.t_submit
    if prefill_dur > 0:
        rows.append(
            ResultRow(
                **common,
                phase="prefill",
                metric_name="prefill_tokens_per_sec",
                metric_component=None,
                value=result.timing.prompt_tokens / prefill_dur,
                unit="tokens_per_sec",
                notes=result.notes,
            )
        )

    # --- ttft_seconds ---
    rows.append(
        ResultRow(
            **common,
            phase="prefill",
            metric_name="ttft_seconds",
            metric_component=None,
            value=prefill_dur,
            unit="seconds",
            notes=result.notes,
        )
    )

    # --- decode_tokens_per_sec ---
    decode_dur = result.timing.t_last_token - result.timing.t_first_token
    if decode_dur > 0 and result.timing.decode_tokens > 0:
        rows.append(
            ResultRow(
                **common,
                phase="decode",
                metric_name="decode_tokens_per_sec",
                metric_component=None,
                value=result.timing.decode_tokens / decode_dur,
                unit="tokens_per_sec",
                notes=result.notes,
            )
        )

    # --- peak_memory_bytes (per component, per phase) ---
    for snap in result.memory:
        rows.append(
            ResultRow(
                **common,
                phase=snap.phase,
                metric_name="peak_memory_bytes",
                metric_component=snap.component,
                value=snap.peak_bytes,
                unit="bytes",
                notes=result.notes,
            )
        )

    # --- energy_joules_per_token ---
    if result.energy_prefill_joules is not None and result.timing.prompt_tokens > 0:
        rows.append(
            ResultRow(
                **common,
                phase="prefill",
                metric_name="energy_joules_per_token",
                metric_component=None,
                value=result.energy_prefill_joules / result.timing.prompt_tokens,
                unit="joules_per_token",
                notes=result.notes,
            )
        )
    if result.energy_decode_joules is not None and result.timing.decode_tokens > 0:
        rows.append(
            ResultRow(
                **common,
                phase="decode",
                metric_name="energy_joules_per_token",
                metric_component=None,
                value=result.energy_decode_joules / result.timing.decode_tokens,
                unit="joules_per_token",
                notes=result.notes,
            )
        )

    return rows


def run_sweep(
    backend: InferenceBackend,
    config: HarnessConfig,
    progress: bool = True,
) -> list[ResultRow]:
    """Run the full context sweep and return all rows.

    For each context length: run ``warmups`` discarded iterations, then
    ``repeats`` timed iterations.  Each repeat produces one or more
    ResultRow objects (one per metric × phase × component combination).
    """
    all_rows: list[ResultRow] = []

    for ctx in config.context_lengths:
        if progress:
            print(
                f"  context={ctx:>7d}  warmups={config.warmups}  repeats={config.repeats} ...",
                end="",
                flush=True,
            )

        # Warmup (results discarded)
        for _w in range(config.warmups):
            run_single(backend, config, ctx, repeat_index=-1)

        # Timed repeats
        for r in range(config.repeats):
            result = run_single(backend, config, ctx, repeat_index=r)
            rows = result_to_rows(result, config, ctx, r, config.repeats)
            all_rows.extend(rows)

        if progress:
            print(" done")

    return all_rows


# ---------------------------------------------------------------------------
# Human-readable summary
# ---------------------------------------------------------------------------


def summarize(rows: list[ResultRow]) -> str:
    """Produce a human-readable percentile summary from collected rows.

    Groups by (context_length, phase, metric_name, metric_component) and
    reports p50, p95, and spread — never a single best run (METRICS.md §9).
    """
    from collections import defaultdict

    groups: dict[tuple, list[float]] = defaultdict(list)
    for row in rows:
        key = (
            row.context_length,
            row.phase,
            row.metric_name,
            row.metric_component or "",
        )
        groups[key].append(row.value)

    lines = []
    lines.append(
        f"{'context':>8}  {'phase':>7}  {'metric':>26}  {'comp':>16}  "
        f"{'p50':>10}  {'p95':>10}  {'spread':>7}"
    )
    lines.append("-" * 100)

    for key in sorted(groups):
        ctx, phase, metric, comp = key
        vals = groups[key]
        p50 = _percentile(vals, 50)
        p95 = _percentile(vals, 95)
        spread = ((p95 - p50) / p50 * 100) if p50 > 0 else float("inf")
        lines.append(
            f"{ctx:>8}  {phase:>7}  {metric:>26}  {comp:>16}  "
            f"{p50:>10.4f}  {p95:>10.4f}  {spread:>6.1f}%"
        )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_context_lengths(s: str) -> list[int]:
    parts = [p.strip() for p in s.split(",")]
    result = []
    for p in parts:
        if not p:
            continue
        try:
            result.append(int(p))
        except ValueError:
            raise argparse.ArgumentTypeError(f"Invalid context length: {p!r}") from None
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m bench.harness",
        description="Benchmark runner: context sweep, warmup, repeats, percentiles.",
    )
    parser.add_argument(
        "--backend",
        default="synthetic",
        help="Inference backend name (default: synthetic for testing).",
    )
    parser.add_argument("--model-checkpoint", required=True, help="HF repo id.")
    parser.add_argument(
        "--context-lengths",
        type=_parse_context_lengths,
        default=list(CANONICAL_CONTEXT_LENGTHS),
        help="Comma-separated context lengths (default: 4096,32768,131072,262144).",
    )
    parser.add_argument("--warmups", type=int, default=3, help="Discarded warmup repeats.")
    parser.add_argument("--repeats", type=int, default=5, help="Timed repeats (min 5).")
    parser.add_argument(
        "--decode-tokens",
        type=int,
        default=256,
        help="Decode tokens to generate (METRICS.md §4: N-1=256).",
    )
    parser.add_argument(
        "--device", required=True, choices=["o6", "generic_aarch64", "x86_reference"]
    )
    parser.add_argument(
        "--engine-gdn",
        required=True,
        choices=["npu", "gpu_vulkan", "gpu_opencl", "cpu", "cuda_reference"],
    )
    parser.add_argument(
        "--engine-full-attention",
        required=True,
        choices=["npu", "gpu_vulkan", "gpu_opencl", "cpu", "cuda_reference"],
    )
    parser.add_argument(
        "--quantization", required=True, help="Quantization code, e.g. fp16, int4_w4a16."
    )
    parser.add_argument("--run-id", default="", help="Override auto-generated run_id.")
    parser.add_argument("--output", default="", help="Output CSV path.")
    parser.add_argument(
        "--manifest-ref",
        default="",
        help="Manifest path (default: results/manifests/<run_id>.json).",
    )
    parser.add_argument("--no-progress", action="store_true", help="Suppress progress output.")

    args = parser.parse_args(argv)

    config = HarnessConfig(
        model_checkpoint=args.model_checkpoint,
        device=args.device,
        engine_gdn=args.engine_gdn,
        engine_full_attention=args.engine_full_attention,
        quantization=args.quantization,
        context_lengths=args.context_lengths,
        warmups=args.warmups,
        repeats=args.repeats,
        decode_tokens=args.decode_tokens,
        run_id=args.run_id,
        output=args.output,
        manifest_ref=args.manifest_ref,
    )

    # Select backend
    if args.backend == "synthetic":
        backend = SyntheticBackend()
    else:
        print(f"Error: unknown backend '{args.backend}'. Available: synthetic", file=sys.stderr)
        return 1

    # Run the sweep
    print(f"Benchmark run: {config.run_id}")
    print(f"  model: {config.model_checkpoint}")
    print(
        f"  device: {config.device}  engine_gdn: {config.engine_gdn}  "
        f"engine_full_attn: {config.engine_full_attention}"
    )
    print(f"  quantization: {config.quantization}")
    print(f"  context_lengths: {config.context_lengths}")
    print(f"  warmups: {config.warmups}  repeats: {config.repeats}")
    print()

    rows = run_sweep(backend, config, progress=not args.no_progress)

    # Validate all rows before writing
    for i, row in enumerate(rows):
        try:
            validate_row(row)
        except SchemaValidationError as exc:
            print(f"Schema error on row {i}: {exc}", file=sys.stderr)
            return 1

    # Write CSV
    output_path = config.output or f"results/raw/{config.run_id}.csv"
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    write_csv(rows, output_path)
    print(f"\nWrote {len(rows)} rows to {output_path}")

    # Human-readable summary
    print(f"\n{summarize(rows)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())


# ---------------------------------------------------------------------------
# Backward-compatible API (r5 agent's additions, kept for cross-module compat)
# ---------------------------------------------------------------------------

from dataclasses import dataclass as _dc  # noqa: E402


@_dc(frozen=True)
class ModelConfig:
    """Checkpoint dimensions for analytic memory attribution (METRICS.md §5)."""

    name: str
    num_gdn_layers: int
    num_full_attention_layers: int
    linear_num_value_heads: int
    linear_key_head_dim: int
    linear_value_head_dim: int
    fa_n_kv_heads: int
    fa_head_dim: int
    state_dtype_bytes: int = 4
    cache_dtype_bytes: int = 2
    weight_dtype_bytes: int = 2
    num_params: int = 0
    vocab_size: int = 151936


QWEN35_4B = ModelConfig(
    name="Qwen/Qwen3.5-4B",
    num_gdn_layers=24,
    num_full_attention_layers=8,
    linear_num_value_heads=32,
    linear_key_head_dim=128,
    linear_value_head_dim=128,
    fa_n_kv_heads=4,
    fa_head_dim=256,
    num_params=4_000_000_000,
)

QWEN35_08B = ModelConfig(
    name="Qwen/Qwen3.5-0.8B",
    num_gdn_layers=18,
    num_full_attention_layers=6,
    linear_num_value_heads=16,
    linear_key_head_dim=128,
    linear_value_head_dim=128,
    fa_n_kv_heads=2,
    fa_head_dim=256,
    num_params=800_000_000,
)

# Alias for backward compatibility
SweepConfig = HarnessConfig
Backend = InferenceBackend

# Renamed run_single for backward compatibility
run_one_repeat = run_single
