#!/usr/bin/env python3
"""Generate the e2e fleet comparison table from committed schema CSVs.

Reads every results/raw/*_e2e_schema.csv, extracts decode tok/s and TTFT,
groups by model + quantization, and emits a markdown table to
results/figures/e2e_fleet_comparison.md.

Flags commit mismatches per RESULTS DISCIPLINE: devices measured at
different commits are not comparable.

Bead ob-52r. Run after all fleet devices have re-run at the matched commit.

Usage:
    python3 scripts/gen_e2e_comparison.py
    python3 scripts/gen_e2e_comparison.py --output results/figures/e2e_fleet_comparison.md
"""

import csv
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = REPO_ROOT / "results" / "raw"
DEFAULT_OUT = REPO_ROOT / "results" / "figures" / "e2e_fleet_comparison.md"


def load_rows():
    """Load all e2e schema CSVs and return a list of dicts."""
    rows = []
    for f in sorted(RAW_DIR.glob("*_e2e_schema.csv")):
        with open(f) as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                rows.append(row)
    return rows


def extract_metrics(rows):
    """Extract tok/s and TTFT per device/model/quant, keyed by (device, model, quant)."""
    data = defaultdict(
        lambda: {"tok_per_sec": [], "ttft": [], "sha": set(), "manifests": set(), "runs": 0}
    )
    for r in rows:
        device = r.get("device", "?")
        model = r.get("model_checkpoint", "?")
        # Shorten model name
        if "4B" in model:
            model_short = "4B"
        elif "0.8B" in model:
            model_short = "0.8B"
        else:
            model_short = model.split("/")[-1] if "/" in model else model
        quant = r.get("quantization", "fp32")
        sha = r.get("git_sha", "?")[:8]

        key = (device, model_short, quant)
        entry = data[key]
        entry["sha"].add(sha)
        entry["manifests"].add(r.get("manifest_ref", ""))
        entry["runs"] = max(entry["runs"], int(r.get("repeat_count", "1")))

        metric = r.get("metric_name", "")
        val = r.get("value", "")
        try:
            val = float(val)
        except (ValueError, TypeError):
            continue

        if metric == "decode_tokens_per_sec":
            entry["tok_per_sec"].append(val)
        elif metric == "ttft_seconds":
            # Convert to ms for readability
            entry["ttft"].append(val * 1000)

    return data


def fmt_mean_std(vals):
    if not vals:
        return "—"
    mean = sum(vals) / len(vals)
    if len(vals) > 1:
        std = (sum((v - mean) ** 2 for v in vals) / len(vals)) ** 0.5
        if std / mean > 0.01:  # Show std only if >1%
            return f"{mean:.2f} ± {std:.2f}"
    return f"{mean:.2f}"


def generate_table(data):
    """Generate markdown table from extracted metrics."""
    lines = []

    # Group by (model, quant)
    groups = defaultdict(list)
    for (device, model, quant), entry in sorted(data.items()):
        groups[(model, quant)].append((device, entry))

    lines.append("# E2E Decode Fleet Comparison")
    lines.append("")
    lines.append("Generated by `scripts/gen_e2e_comparison.py`. Do not hand-edit.")
    lines.append("")

    # Commit mismatch check
    all_shas = set()
    for entry in data.values():
        all_shas.update(entry["sha"])
    if len(all_shas) > 1:
        lines.append("> ⚠️ **Commit mismatch detected.** Devices measured at different commits")
        lines.append("> are not comparable (RESULTS DISCIPLINE, bead ob-bf7).")
        lines.append(f"> Commits in play: {', '.join(sorted(all_shas))}")
        lines.append("")

    for (model, quant), entries in sorted(groups.items()):
        title = f"Qwen3.5-{model} — {quant.upper()}"
        lines.append(f"## {title}")
        lines.append("")

        # Table header
        lines.append("| Device | Commit | Tok/s | TTFT (ms) | Runs | Notes |")
        lines.append("|--------|--------|------:|----------:|-----:|-------|")

        for device, entry in entries:
            sha_str = ", ".join(sorted(entry["sha"]))
            tok = fmt_mean_std(entry["tok_per_sec"])
            ttft = fmt_mean_std(entry["ttft"])
            runs = entry["runs"]
            notes = []
            if len(entry["sha"]) > 1:
                notes.append("⚠ multi-commit")
            if any("dirty" in m for m in entry["manifests"]):
                notes.append("⚠ dirty")
            notes_str = "; ".join(notes) if notes else ""
            lines.append(f"| {device} | `{sha_str}` | {tok} | {ttft} | {runs} | {notes_str} |")

        lines.append("")

    # Cross-quantization comparison (if both fp32 and int8 exist for same device/model)
    # Normalize device names: strip _int8 suffix, match big-cluster FP32 (no suffix) to big INT8
    fp32_map = {}  # (normalized_device, model) -> entry
    for (device, model, quant), entry in data.items():
        if quant == "fp32":
            # FP32 without cluster suffix = big cluster (default)
            norm = device
            fp32_map[(norm, model)] = entry
            # Also try with _big appended for matching
            if "_big" not in device and "_little" not in device:
                fp32_map[(device + "_big", model)] = entry

    int8_entries = {k: v for k, v in data.items() if k[2] == "int8"}
    if int8_entries:
        lines.append("## INT8 vs FP32 Speedup")
        lines.append("")
        lines.append("| Device | Model | FP32 tok/s | INT8 tok/s | Speedup |")
        lines.append("|--------|-------|-----------:|-----------:|--------:|")

        for (device, model, _), i_entry in sorted(int8_entries.items()):
            # Normalize: strip _int8 from device name for matching
            norm_device = device.replace("_int8", "")
            fp32_key = (norm_device, model)
            if fp32_key in fp32_map:
                f_entry = fp32_map[fp32_key]
                fp32_tok = (
                    sum(f_entry["tok_per_sec"]) / len(f_entry["tok_per_sec"])
                    if f_entry["tok_per_sec"]
                    else 0
                )
                int8_tok = (
                    sum(i_entry["tok_per_sec"]) / len(i_entry["tok_per_sec"])
                    if i_entry["tok_per_sec"]
                    else 0
                )
                speedup = int8_tok / fp32_tok if fp32_tok > 0 else 0
                lines.append(
                    f"| {device} | {model} | {fp32_tok:.2f} | {int8_tok:.2f} | **{speedup:.2f}×** |"
                )
            else:
                int8_tok = (
                    sum(i_entry["tok_per_sec"]) / len(i_entry["tok_per_sec"])
                    if i_entry["tok_per_sec"]
                    else 0
                )
                lines.append(f"| {device} | {model} | — | {int8_tok:.2f} | — |")

        lines.append("")

    lines.append("## Data Sources")
    lines.append("")
    for f in sorted(RAW_DIR.glob("*_e2e_schema.csv")):
        lines.append(f"- `{f.relative_to(REPO_ROOT)}`")
    lines.append("")

    return "\n".join(lines)


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Generate e2e fleet comparison table")
    parser.add_argument(
        "--output",
        "-o",
        default=str(DEFAULT_OUT),
        help="Output markdown file (default: results/figures/e2e_fleet_comparison.md)",
    )
    args = parser.parse_args()

    rows = load_rows()
    if not rows:
        print("ERROR: no *_e2e_schema.csv files found in results/raw/", file=sys.stderr)
        sys.exit(1)

    data = extract_metrics(rows)
    markdown = generate_table(data)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(markdown)
    print(f"Written: {out_path}")
    print(f"  Devices: {len(set(r.get('device', '?') for r in rows))}")
    print(f"  Data rows: {len(rows)}")

    # Warn about commit mismatches
    all_shas = set()
    for entry in data.values():
        all_shas.update(entry["sha"])
    if len(all_shas) > 1:
        print(f"\n⚠ WARNING: {len(all_shas)} different commits in the data:")
        for sha in sorted(all_shas):
            print(f"  {sha}")
        print("Devices at different commits are NOT comparable.")


if __name__ == "__main__":
    main()
